#!/usr/bin/env bash
# This script 
while IFS=: read -r username pass uid gid gcose home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $gcose"
done < /etc/passwd
